language: rust
rust: stable
node_js: "node"
before_install:
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli
jobs:
  include:
    - stage: Install
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit-tests
      script: npm run test
