language: rust
rust: stable
node_js: "10"

before_install: 
  - rustup target add wasm32-unknown-unknown
  - if [ ! -f "/home/travis/.cargo/bin/wasm-pack" ]; then
      curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh;
    fi
  - if [ ! -d "/home/travis/.nvm/versions/node/v10.15.0" ]; then
      nvm install 10.15.0;
    fi
  - nvm use 10.15.0

cache:
  cargo: true
  directories:
    - node_modules
    - .target
    - ./wasm
    - ~/.cargo
    - ~/.nvm

jobs:
  include:
    - stage: Install
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit tests
      script: npm run test

notifications:
  email: false