language: rust
rust: stable
node_js: "10.15"

env:
  - WASM_BIN = $(which wasm-bindgen)

before_install: 
  - rustup target add wasm32-unknown-unknown
  - if [ ! -f "/home/travis/.cargo/bin/wasm-bindgen" ]; then
      cargo install -f wasm-bindgen-cli --version 0.2.33;
    fi

cache:
  cargo: true
  directories:
    - node_modules
    - ./src/rsa_rs/target
    - ./wasm
    - ~/.cargo

jobs:
  include:
    - stage: Install
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit tests
      script: npm run test

