language: rust
rust: stable
node_js: "10"

install: 
  - rustup target add wasm32-unknown-unknown

cache:
  directories:
    - node_modules
    - src/rsa_rs/target
    - ~/.cargo/bin

jobs:
  include:
    - stage: Build
      scripts:
        - cargo install wasm-bindgen-cli
        - npm install
        - npm run build
    - stage: Unit tests
      script: npm run test

