language: rust
rust: stable
node_js: "10"

before_install: 
  - rustup target add wasm32-unknown-unknown

jobs:
  include:
    - stage: Install
      install: cargo install -f wasm-bindgen-cli
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit tests
      script: npm run test

