matrix:
  include:
    - language: rust
      rust: stable
      script:
        - rustup target add wasm32-unknown-unknown
        - cargo check --target wasm32-unknown-unknown
        - cargo install wasm-bindgen-cli
