language: rust
rust: stable
node_js: "10"

script: skip
before_install: 
  - rustup target add wasm32-unknown-unknown
  
cache:
  cargo: true
  directories:
    - node_modules
    - ./src/rsa_rs/target
    - ./wasm
    - ~/.cargo/bin

jobs:
  include:
    - stage: Pre-install
    - stage: Build
      scripts:
        - cargo install wasm-bindgen-cli --force
        - npm install
        - npm run build
    - stage: Unit tests
      script: npm run test

