language: rust
rust: stable
node_js: "10"
before_install: 
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli
  - npm install

cache:
  directories:
    - node_modules
    - src/rsa_rs/target
    - ~/.cargo/bin

jobs:
  include:
    - stage: Build job
    - script: npm run build
    - stage: Unit tests
    - script: npm run test

