language: rust
rust: stable
jobs:
  include:
    - stage: Pre-install 
      script:
        - rustup target add wasm32-unknown-unknown
        - cargo install wasm-bindgen-cli
    - stage: Install
      node_js: "node"
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit-tests
      script: npm run test
