language: rust
rust: stable
node_js: "10"
env:
  - CLI_EXISTS = $(which wasm-bindgen-cli)

before_install: 
  - rustup target add wasm32-unknown-unknown
  - if [ $CLI_EXISTS == "" ]; then
      cargo install -f wasm-bindgen-cli --version 0.2.33
    fi

cache:
  cargo: true
  directories:
    - node_modules
    - ./src/rsa_rs/target
    - ./wasm
    - ~/.cargo/bin

jobs:
  include:
    - stage: Install
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Unit tests
      script: npm run test

