language: node_js
rust: stable
node_js: "10"

before_install: 
  - rustup target add wasm32-unknown-unknown
  
cache:
  cargo: true
  directories:
    - node_modules
    - ./src/rsa_rs/target
    - ./wasm
    - ~/.cargo/bin

jobs:
  include:
    - stage: Build
      install:
        - cargo install wasm-bindgen-cli --force
      scripts:
        - npm install
        - npm run build
    - stage: Unit tests
      script: npm run test

