language: rust
rust: stable
node_js: "10"
before_install: rustup target add wasm32-unknown-unknown

jobs:
  include:
    - stage: All checks
      name: "Install"
      scripts:
        - cargo install wasm-bindgen-cli
        - npm install
    - script: npm run build
      name: "Build"
    - script: npm run test
      name: "Unit tests"